name: Continuous Deployment Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/FacilityAreaManager.Backend/**"

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api:
          - name: "Facility Area Manager API"
            path: "FacilityAreaManagerApi"
            azure_app_name: "facilityareamanager-api-germanywestcentral-001"
            publish_secret: FACILITY_AREA_MANAGER_API_PUBLISH_SECRET

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: |
          dotnet restore src/FacilityAreaManager.Backend/FacilityAreaManager.Backend.sln

      - name: Build projects
        run: |
          dotnet build src/FacilityAreaManager.Backend/FacilityAreaManager.Backend.sln

      - name: Run tests
        run: |
          dotnet test src/FacilityAreaManager.Backend/FacilityAreaManager.Backend.sln

      - name: Publish
        run: dotnet publish src/FacilityAreaManager.Backend/${{ matrix.api.path }} --configuration Release --output ./src/FacilityAreaManager.Backend/${{ matrix.api.path }}/publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ matrix.api.azure_app_name }}
          slot-name: "production"
          publish-profile: ${{ secrets[matrix.api.publish_secret] }}
          package: ./src/FacilityAreaManager.Backend/${{ matrix.api.path }}/publish
